<?php if (!isset($_SESSION['user'])) : ?>
    <!--no user navigation header-->
    <nav class="nav-no-user">
        <div class="red align-center nav-element" onclick="window.location.href = '/'">Multiplex Track</div>
        <div class="align-center">No User</div>
        <div class="align-center">
            <button class="open-button" onclick="openForm()">Login</button>
        </div>
    </nav>
<?php include __ROOT__ . 'app/frontend/User/login.phtml'; endif;?>

<?php if (isset($_SESSION['user']) && $_SESSION['user']->getType() == 1) : ?>
    <!--regular user navigation header-->
    <nav class="nav-user">
        <div class="red align-center nav-element" onclick="window.location.href = '/'">Multiplex Track</div>
        <div class="align-center">Regular User</div>
        <button class="open-button align-center nav-end-element" onclick="window.location.href = '/user/logout'">Logout</button>
    </nav>
<?php endif; ?>

<?php if (isset($_SESSION['user']) && $_SESSION['user']->getType() == 2) : ?>
    <!--admin user navigation header-->
    <nav class="nav-admin">
        <div class="red align-center nav-element" onclick="window.location.href = '/'">Multiplex Track</div>
        <div class="align-center">Admin User</div>
        <button class="open-button align-center" onclick="changeTitle('Reports'); getReportsPage()">Reports</button>
        <button class="open-button align-center" onclick="changeTitle('Schedules'); getEmptySchedule();">Schedules</button>
        <button class="open-button align-center" onclick="changeTitle('Movies'); getMovies();">Movies</button>
        <button class="open-button align-center nav-end-element" onclick="window.location.href = '/user/logout'">Logout</button>
    </nav>
<?php endif; ?>
