<div id="schedule-container" class="week-grid">
    <?php for ($i = 1; $i <= 7; $i++) : ?>
    <div id="day-<?php echo $i?>" class="day-grid">
        <?php for ($j = 9; $j <= 17; $j++) : ?>
            <?php for ($x = 1; $x <= 2; $x++) : ?>
            <div id="day-<?php echo $i . '-hour-' . $j; if ($x == 1): echo ':00'; else : echo ':30'; endif;?>" class="time-slot-hour-grid">
                <div class="blue-time"><?php echo $j; if ($x == 1): echo ':00'; else : echo ':30'; endif;?></div>
                <?php if (($j == 9) && ($x == 1)) : ?>
                <div id="add-movie-schedule-container-day-<?php echo $i . '-hour-' . $j; if ($x == 1): echo ':00'; else : echo ':30'; endif;?>">
                    <div class="add-movie-grid">
                        <input type="text"
                               onkeyup="
                                   showDropdown('<?php echo 'day-' . $i . '-hour-' . $j; if ($x == 1): echo ':00'; else : echo ':30'; endif;?>');
                                   getMovieByTitle('<?php echo 'day-' . $i . '-hour-' . $j; if ($x == 1): echo ':00'; else : echo ':30'; endif;?>');
                                   "
                               />
                        <button onclick="scheduleMovie('<?php echo $i . '-hour-' . $j; if ($x == 1): echo ':00'; else : echo ':30'; endif;?>')">+</button>
                    </div>
                    <div class="add-movie-dropdown" id="add-movie-dropdown-<?php echo 'day-' . $i . '-hour-' . $j; if ($x == 1): echo ':00'; else : echo ':30'; endif;?>"></div>
                </div>
                <?php endif; ?>
            </div>
            <?php endfor; ?>
        <?php endfor; ?>
    </div>
    <?php endfor; ?>
</div>