<div>
    <div>Invoice Nr: %d</div>
    <div>Screen: %d</div>
    <div>Start at: %s</div>
    <table>
        <tr>
            <th>Movie</th>
            <th>Type</th>
            <th>Nr seats</th>
            <th>Friday Discount</th>
            <th>Total Price</th>
        </tr>
        <tr>
            <td>%s</td>
            <td>%s</td>
            <td>%d</td>
            <td>%s</td>
            <td>$ %s</td>
        </tr>
    </table>
</div>