<div id="add-movie-modal" class="movie-modal">
    <form action="" class="movie-modal-content">
        <div class="field-horizontal-grid">
            <span></span>
            <h3 class="grid-justify-center">Add Movie</h3>
            <span class="close" onclick="closeModal();">&times;</span>
        </div>
        <label for="title">Movie Title
            <input type="text" id="title" name="title" class="field-width" placeholder="Insert movie title">
        </label>
        <label for="year">Movie Year
            <input type="number" id="year" name="year" placeholder="Launch year">
        </label>
        <label for="movie-type">Movie Format
            <select name="type" id="movie-type">
                <option value="2D" selected>2D</option>
                <option value="3D">3D</option>
            </select>
        </label>
        <label for="duration">Time Duration
            <input type="text" id="duration" name="duration" placeholder="Movie Duration in minutes">
        </label>
        <label for="categories">Movie Categories
            <input type="text" id="categories" name="categories" class="field-width" placeholder="Insert categories separated by commas">
        </label>
        <label for="poster">Movie Poster
            <input type="file" id="poster" name="poster">
        </label>
        <div class="field-vertical-grid">
            <label for="description">Movie Short Description</label>
            <textarea name="description" id="description" cols="30" rows="10"></textarea>
        </div>
        <button type="submit">Add Movie</button>
    </form>
</div>