<?php
/**
 * @var $currentMovies
 */
?>
<div class="watch-today-grid">
    <?php if (gettype($currentMovies) == 'array'): ?>
        <?php foreach ($currentMovies as $movie): ?>
            <div>
                <img class="movie-image" src="images/<?php echo $movie['poster']; ?>" alt="dummy_poster"
                     <?php if (isset($_SESSION['user'])): ?>
                     onclick="showWatchTodayModal(<?php echo $movie['id']; ?>)"
                     <?php endif; ?>
                >
                <div class="movie-title"><?php echo $movie['title']; ?></div>
            </div>
        <?php endforeach; ?>
    <?php else: ?>
        <div>No movies available today!</div>
    <?php endif;?>
</div>